//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikra_Is_Yonetim._3rdApp.Oztek {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OztekSmsWebService", ConfigurationName="Oztek.OztekSmsWebServicePortType")]
    public interface OztekSmsWebServicePortType {
        
        // CODEGEN: TekSmsiBirdenCokNumarayaGonderRequest iletisinin uyarlama ad alanı (urn:TekSmsiBirdenCokNumarayaGonder) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#TekSmsiBirdenCokNumarayaGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse TekSmsiBirdenCokNumarayaGonder(Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#TekSmsiBirdenCokNumarayaGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse> TekSmsiBirdenCokNumarayaGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest request);
        
        // CODEGEN: HerBirNumarayaFarkliSmsGonderRequest iletisinin uyarlama ad alanı (urn:HerBirNumarayaFarkliSmsGonder) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#HerBirNumarayaFarkliSmsGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse HerBirNumarayaFarkliSmsGonder(Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#HerBirNumarayaFarkliSmsGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse> HerBirNumarayaFarkliSmsGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest request);
        
        // CODEGEN: SmsiptaletRequest iletisinin uyarlama ad alanı (urn:Smsiptalet) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#Smsiptalet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse Smsiptalet(Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#Smsiptalet", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse> SmsiptaletAsync(Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest request);
        
        // CODEGEN: OrjinatorGonderRequest iletisinin uyarlama ad alanı (urn:OrjinatorGonder) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse OrjinatorGonder(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse> OrjinatorGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest request);
        
        // CODEGEN: RaporSorgulaRequest iletisinin uyarlama ad alanı (urn:RaporSorgula) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#RaporSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse RaporSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#RaporSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse> RaporSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest request);
        
        // CODEGEN: UyeBilgisiSorgulaRequest iletisinin uyarlama ad alanı (urn:UyeBilgisiSorgula) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#UyeBilgisiSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse UyeBilgisiSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#UyeBilgisiSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse> UyeBilgisiSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest request);
        
        // CODEGEN: OrjinatorSorgulaRequest iletisinin uyarlama ad alanı (urn:OrjinatorSorgula) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse OrjinatorSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse> OrjinatorSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest request);
        
        // CODEGEN: GunlukRaporSorgulaRequest iletisinin uyarlama ad alanı (urn:GunlukRaporSorgula) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#GunlukRaporSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse GunlukRaporSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#GunlukRaporSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse> GunlukRaporSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest request);
        
        // CODEGEN: ikitariharasisorgulaXMLverRequest iletisinin uyarlama ad alanı (urn:ikitariharasisorgulaXMLver) varsayılan değerle (urn:OztekSmsWebService) eşleşmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse ikitariharasisorgulaXMLver(Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLver", ReplyAction="*")]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse> ikitariharasisorgulaXMLverAsync(Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekSmsiBirdenCokNumarayaGonder", WrapperNamespace="urn:TekSmsiBirdenCokNumarayaGonder", IsWrapped=true)]
    public partial class TekSmsiBirdenCokNumarayaGonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numaralar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mesaj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string zaman;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string zamanasimi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string tip;
        
        public TekSmsiBirdenCokNumarayaGonderRequest() {
        }
        
        public TekSmsiBirdenCokNumarayaGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.numaralar = numaralar;
            this.mesaj = mesaj;
            this.zaman = zaman;
            this.zamanasimi = zamanasimi;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekSmsiBirdenCokNumarayaGonderResponse", WrapperNamespace="urn:TekSmsiBirdenCokNumarayaGonder", IsWrapped=true)]
    public partial class TekSmsiBirdenCokNumarayaGonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public TekSmsiBirdenCokNumarayaGonderResponse() {
        }
        
        public TekSmsiBirdenCokNumarayaGonderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HerBirNumarayaFarkliSmsGonder", WrapperNamespace="urn:HerBirNumarayaFarkliSmsGonder", IsWrapped=true)]
    public partial class HerBirNumarayaFarkliSmsGonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numaramesaj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string zaman;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string zamanasimi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string tip;
        
        public HerBirNumarayaFarkliSmsGonderRequest() {
        }
        
        public HerBirNumarayaFarkliSmsGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.numaramesaj = numaramesaj;
            this.zaman = zaman;
            this.zamanasimi = zamanasimi;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HerBirNumarayaFarkliSmsGonderResponse", WrapperNamespace="urn:HerBirNumarayaFarkliSmsGonder", IsWrapped=true)]
    public partial class HerBirNumarayaFarkliSmsGonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public HerBirNumarayaFarkliSmsGonderResponse() {
        }
        
        public HerBirNumarayaFarkliSmsGonderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Smsiptalet", WrapperNamespace="urn:Smsiptalet", IsWrapped=true)]
    public partial class SmsiptaletRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ozelid;
        
        public SmsiptaletRequest() {
        }
        
        public SmsiptaletRequest(string kullanicino, string kullaniciadi, string sifre, string ozelid) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.ozelid = ozelid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsiptaletResponse", WrapperNamespace="urn:Smsiptalet", IsWrapped=true)]
    public partial class SmsiptaletResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SmsiptaletResponse() {
        }
        
        public SmsiptaletResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorGonder", WrapperNamespace="urn:OrjinatorGonder", IsWrapped=true)]
    public partial class OrjinatorGonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string aciklama;
        
        public OrjinatorGonderRequest() {
        }
        
        public OrjinatorGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.aciklama = aciklama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorGonderResponse", WrapperNamespace="urn:OrjinatorGonder", IsWrapped=true)]
    public partial class OrjinatorGonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public OrjinatorGonderResponse() {
        }
        
        public OrjinatorGonderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RaporSorgula", WrapperNamespace="urn:RaporSorgula", IsWrapped=true)]
    public partial class RaporSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ozelid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numara;
        
        public RaporSorgulaRequest() {
        }
        
        public RaporSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.ozelid = ozelid;
            this.numara = numara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RaporSorgulaResponse", WrapperNamespace="urn:RaporSorgula", IsWrapped=true)]
    public partial class RaporSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RaporSorgulaResponse() {
        }
        
        public RaporSorgulaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UyeBilgisiSorgula", WrapperNamespace="urn:UyeBilgisiSorgula", IsWrapped=true)]
    public partial class UyeBilgisiSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        public UyeBilgisiSorgulaRequest() {
        }
        
        public UyeBilgisiSorgulaRequest(string kullanicino, string kullaniciadi, string sifre) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UyeBilgisiSorgulaResponse", WrapperNamespace="urn:UyeBilgisiSorgula", IsWrapped=true)]
    public partial class UyeBilgisiSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UyeBilgisiSorgulaResponse() {
        }
        
        public UyeBilgisiSorgulaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorSorgula", WrapperNamespace="urn:OrjinatorSorgula", IsWrapped=true)]
    public partial class OrjinatorSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        public OrjinatorSorgulaRequest() {
        }
        
        public OrjinatorSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorSorgulaResponse", WrapperNamespace="urn:OrjinatorSorgula", IsWrapped=true)]
    public partial class OrjinatorSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public OrjinatorSorgulaResponse() {
        }
        
        public OrjinatorSorgulaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GunlukRaporSorgula", WrapperNamespace="urn:GunlukRaporSorgula", IsWrapped=true)]
    public partial class GunlukRaporSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tarih;
        
        public GunlukRaporSorgulaRequest() {
        }
        
        public GunlukRaporSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string tarih) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GunlukRaporSorgulaResponse", WrapperNamespace="urn:GunlukRaporSorgula", IsWrapped=true)]
    public partial class GunlukRaporSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GunlukRaporSorgulaResponse() {
        }
        
        public GunlukRaporSorgulaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLver", WrapperNamespace="urn:ikitariharasisorgulaXMLver", IsWrapped=true)]
    public partial class ikitariharasisorgulaXMLverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string baslangictarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string bitistarih;
        
        public ikitariharasisorgulaXMLverRequest() {
        }
        
        public ikitariharasisorgulaXMLverRequest(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih) {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.baslangictarih = baslangictarih;
            this.bitistarih = bitistarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLverResponse", WrapperNamespace="urn:ikitariharasisorgulaXMLver", IsWrapped=true)]
    public partial class ikitariharasisorgulaXMLverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ikitariharasisorgulaXMLverResponse() {
        }
        
        public ikitariharasisorgulaXMLverResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OztekSmsWebServicePortTypeChannel : Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OztekSmsWebServicePortTypeClient : System.ServiceModel.ClientBase<Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType>, Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType {
        
        public OztekSmsWebServicePortTypeClient() {
        }
        
        public OztekSmsWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OztekSmsWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OztekSmsWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OztekSmsWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.TekSmsiBirdenCokNumarayaGonder(Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest request) {
            return base.Channel.TekSmsiBirdenCokNumarayaGonder(request);
        }
        
        public string TekSmsiBirdenCokNumarayaGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip) {
            Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaralar = numaralar;
            inValue.mesaj = mesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).TekSmsiBirdenCokNumarayaGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.TekSmsiBirdenCokNumarayaGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest request) {
            return base.Channel.TekSmsiBirdenCokNumarayaGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderResponse> TekSmsiBirdenCokNumarayaGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip) {
            Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.TekSmsiBirdenCokNumarayaGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaralar = numaralar;
            inValue.mesaj = mesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).TekSmsiBirdenCokNumarayaGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.HerBirNumarayaFarkliSmsGonder(Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest request) {
            return base.Channel.HerBirNumarayaFarkliSmsGonder(request);
        }
        
        public string HerBirNumarayaFarkliSmsGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip) {
            Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaramesaj = numaramesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).HerBirNumarayaFarkliSmsGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.HerBirNumarayaFarkliSmsGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest request) {
            return base.Channel.HerBirNumarayaFarkliSmsGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderResponse> HerBirNumarayaFarkliSmsGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip) {
            Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.HerBirNumarayaFarkliSmsGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaramesaj = numaramesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).HerBirNumarayaFarkliSmsGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.Smsiptalet(Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest request) {
            return base.Channel.Smsiptalet(request);
        }
        
        public string Smsiptalet(string kullanicino, string kullaniciadi, string sifre, string ozelid) {
            Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).Smsiptalet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.SmsiptaletAsync(Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest request) {
            return base.Channel.SmsiptaletAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletResponse> SmsiptaletAsync(string kullanicino, string kullaniciadi, string sifre, string ozelid) {
            Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.SmsiptaletRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).SmsiptaletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.OrjinatorGonder(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest request) {
            return base.Channel.OrjinatorGonder(request);
        }
        
        public string OrjinatorGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama) {
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.aciklama = aciklama;
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).OrjinatorGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.OrjinatorGonderAsync(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest request) {
            return base.Channel.OrjinatorGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderResponse> OrjinatorGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama) {
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.aciklama = aciklama;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).OrjinatorGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.RaporSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest request) {
            return base.Channel.RaporSorgula(request);
        }
        
        public string RaporSorgula(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara) {
            Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            inValue.numara = numara;
            Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).RaporSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.RaporSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest request) {
            return base.Channel.RaporSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaResponse> RaporSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara) {
            Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.RaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            inValue.numara = numara;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).RaporSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.UyeBilgisiSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest request) {
            return base.Channel.UyeBilgisiSorgula(request);
        }
        
        public string UyeBilgisiSorgula(string kullanicino, string kullaniciadi, string sifre) {
            Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).UyeBilgisiSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.UyeBilgisiSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest request) {
            return base.Channel.UyeBilgisiSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaResponse> UyeBilgisiSorgulaAsync(string kullanicino, string kullaniciadi, string sifre) {
            Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.UyeBilgisiSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).UyeBilgisiSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.OrjinatorSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest request) {
            return base.Channel.OrjinatorSorgula(request);
        }
        
        public string OrjinatorSorgula(string kullanicino, string kullaniciadi, string sifre, string orjinator) {
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).OrjinatorSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.OrjinatorSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest request) {
            return base.Channel.OrjinatorSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaResponse> OrjinatorSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator) {
            Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.OrjinatorSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).OrjinatorSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.GunlukRaporSorgula(Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest request) {
            return base.Channel.GunlukRaporSorgula(request);
        }
        
        public string GunlukRaporSorgula(string kullanicino, string kullaniciadi, string sifre, string tarih) {
            Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.tarih = tarih;
            Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).GunlukRaporSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.GunlukRaporSorgulaAsync(Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest request) {
            return base.Channel.GunlukRaporSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaResponse> GunlukRaporSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string tarih) {
            Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.GunlukRaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.tarih = tarih;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).GunlukRaporSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.ikitariharasisorgulaXMLver(Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest request) {
            return base.Channel.ikitariharasisorgulaXMLver(request);
        }
        
        public string ikitariharasisorgulaXMLver(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih) {
            Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse retVal = ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLver(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse> Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType.ikitariharasisorgulaXMLverAsync(Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest request) {
            return base.Channel.ikitariharasisorgulaXMLverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverResponse> ikitariharasisorgulaXMLverAsync(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih) {
            Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest inValue = new Ikra_Is_Yonetim._3rdApp.Oztek.ikitariharasisorgulaXMLverRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            return ((Ikra_Is_Yonetim._3rdApp.Oztek.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLverAsync(inValue);
        }
    }
}
