// <auto-generated />
namespace Ikra_Is_Yonetim.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ikradbv50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ikradbv50));
        
        string IMigrationMetadata.Id
        {
            get { return "201908121407371_ikradb-v50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
