// <auto-generated />
namespace Ikra_Is_Yonetim.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ikradbv44 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ikradbv44));
        
        string IMigrationMetadata.Id
        {
            get { return "201908121224121_ikradb-v44"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
